
variables:
  repo_path: './_dclone'

log_path: './depy.log'
stamp_path: '${{ variables.repo_path }}/depy.stamp'

repository:
  force_rebuild: true
  init: true
  path: ${{ variables.repo_path }}
  url: 'https://github.com/sidneydijkstra/Depy.git'
  branch: test

stages:
  - pull
  - test

jobs:
  pull:
    steps:
      # Pull out the repository
      #- pull
      # Build the project using a specified script
      #- run: init_script.sh
      - service-create:
          name: myservice
          directory: /var/myservice
          description: The description of myservice
          command: sudo python ./myservice.py
  test:
    steps:
      # Run tests using the specified test command
      #- run: |
      #    echo "this is a test"

sleep_time: 5

mailer:
  enable: False
  url: 'smtp.example.com'
  user: 'user@example.com'
  password: 'password'
  to: 'recipient@example.com'
