
variables:
  repo_path: './_dclone'

log_path: './depy.log'
stamp_path: '${{ variables.repo_path }}/depy.stamp'

repository:
  path: ${{ variables.repo_path }}
  url: 'https://github.com/sidneydijkstra/Depy.git'
  branch: test

stages:
  - pull
  - test

jobs:
  pull:
    steps:
      # Pull out the repository
      - pull
      # Build the project using a specified script
      - run: init_script.sh
          
  test:
    steps:
      # Run tests using the specified test command
      - run: |
          echo "this is a test"

sleep_time: 30

mailer:
  enable: False
  url: 'smtp.example.com'
  user: 'user@example.com'
  password: 'password'
  to: 'recipient@example.com'
